- name: instalar kibana fedora
  include: kibana-fedora.yml
  when: ansible_distribution == "Fedora" or ansible_distribution == "CentOS"

- name: iniciamos y habilitamos el servicio httpd
  service: name=kibana state=started enabled=true
